services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.13
    ports:
      - "26257:26257"
      - "8080:8080"
    entrypoint: 
      - /bin/sh
    command:
      - -c
      - '/cockroach/cockroach.sh start-single-node --insecure'
  sql-proxy:
    image: ghcr.io/droptableifexists/sql-proxy:latest
    ports:
      - "26258:26258"
      - "12345:12345"
    environment:
      - DB_CONNECTION_STRING=host=cockroachdb port=26257 user=root dbname=defaultdb sslmode=disable
      - LISTEN_PORT=26258
      - BACKEND_HOST=cockroachdb
      - BACKEND_PORT=26257
      - API_PORT=12345
